-- Add migration script here

CREATE TYPE food_stat AS ENUM('active','removed','out of stock');

CREATE TABLE user_details (
  -- Timestamps
  cid varchar(128) NOT NULL,
  ctime TIMESTAMP WITH TIME ZONE,
  mid varchar(128) NOT NULL,
  mtime TIMESTAMP WITH TIME ZONE,

  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 2000) PRIMARY KEY,

  stamp_code varchar(128) NOT NULL,

  foods_table varchar(128) NOT NULL,
  category varchar(128) NOT NULL,
  stocks int NOT NULL,
  price float NOT NULL,
  total_quantity int NOT NULL,
  food_status food_stat DEFAULT 'active'
);
